# Generated by Django 3.0.4 on 2020-03-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
