# Generated by Django 3.0.4 on 2020-04-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200325_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parkingspot',
            options={'verbose_name': 'Parking Spot'},
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='email',
            field=models.CharField(default='admin@parkio.com', max_length=100),
            preserve_default=False,
        ),
    ]
