# Generated by Django 3.0.4 on 2020-04-12 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200412_0414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingspot',
            old_name='email',
            new_name='owner_email',
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='reserver_email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
