# Generated by Django 3.0.4 on 2020-04-12 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200412_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='reserver_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
